[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
log = { version = "0.4.14", features = ["max_level_debug", "release_max_level_info"] }
rand = "0.8.4"
